services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      -  "7777:7777"
    env_file:
      - ./server/.env
  
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      -  "5173:5173"
    depends_on:
      - server
    
